# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84839b724e668fd50c405eeb7c40104da12ef0cadf0ae24ad76f2c16f79ebcca919070a85f7a0a5dc7a624fd809d0455d77bec0631f021c8d6b7d9b2a76b6f26

test:
  secret_key_base: d09b23dcc6974ad6dddf29f3050f874b34de010295f8153f8fe9b05de83089f59e7225b6d139454158fbfd5db550cbb6f354c3c559d1c5abc7c30b8456ba9483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
